# Generated by Django 3.1.2 on 2020-10-18 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_auto_20201016_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='comment_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='performance.comments'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='max_time',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='steps',
            name='min_time',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
