# Generated by Django 3.1.2 on 2020-10-18 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_auto_20201018_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='comment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='performance.comments'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='max_time',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='min_time',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
