# Generated by Django 3.1.2 on 2020-10-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_auto_20201019_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vara',
            name='time_macrostep_1',
        ),
        migrations.RemoveField(
            model_name='vara',
            name='time_macrostep_2',
        ),
        migrations.RemoveField(
            model_name='vara',
            name='time_macrostep_3',
        ),
        migrations.RemoveField(
            model_name='vara',
            name='time_macrostep_4',
        ),
        migrations.AddField(
            model_name='vara',
            name='time_baixa_ou_arquivamento',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='vara',
            name='time_conclusao',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='vara',
            name='time_decisao',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='vara',
            name='time_despacho',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='vara',
            name='time_distribuicao',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='vara',
            name='time_julgamento',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='vara',
            name='time_transito_em_julgado',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vara',
            name='latitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vara',
            name='longitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vara',
            name='ranking',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
