# Generated by Django 3.1.2 on 2020-11-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_auto_20201019_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='vara',
            name='time_audiencia',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='vara',
            name='time_citacao',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='vara',
            name='time_outros',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vara',
            name='time_baixa_ou_arquivamento',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vara',
            name='time_conclusao',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vara',
            name='time_decisao',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vara',
            name='time_despacho',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vara',
            name='time_distribuicao',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vara',
            name='time_julgamento',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vara',
            name='time_transito_em_julgado',
            field=models.FloatField(default=None, null=True),
        ),
    ]
