# Generated by Django 3.1.2 on 2020-11-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0007_auto_20201118_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='frequent_classes',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='frequent_subjects',
            field=models.JSONField(null=True),
        ),
    ]
