# Generated by Django 3.1.2 on 2020-11-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0008_auto_20201118_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
