# Generated by Django 3.1.2 on 2020-11-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0009_auto_20201122_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.TextField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='competences',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='subject',
            field=models.TextField(default=None, max_length=255, null=True),
        ),
    ]
