# Generated by Django 3.1.2 on 2020-11-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0010_auto_20201123_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steps',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='steps',
            name='comment_id',
            field=models.ManyToManyField(null=True, to='performance.Comments'),
        ),
    ]
