# Generated by Django 3.1.2 on 2020-11-26 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0011_auto_20201125_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steps',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='steps',
            name='comment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='performance.comments'),
        ),
    ]
